groups/urls.py
from django.urls import path
from . import views

app_name = 'groups'

urlpatterns = [
    path('', views.registerVehicle, name="all"),
    # path("new/", views.CreateGroup.as_view(), name="create"),
    # path("posts/in/<slug>/",views.SingleGroup.as_view(),name="single"),
    # path("join/<slug>/",views.JoinGroup.as_view(),name="join"),
    # path("leave/<slug>/",views.LeaveGroup.as_view(),name="leave"),
]

register/urls.py
from django.urls import path
from . import views

app_name = 'register'

urlpatterns = [
    path('', views.registerfacVehicle, name="all"),
    path('veh/',views.veh)
    # path("new/", views.CreateGroup.as_view(), name="create"),
    # path("posts/in/<slug>/",views.SingleGroup.as_view(),name="single"),
    # path("join/<slug>/",views.JoinGroup.as_view(),name="join"),
    # path("leave/<slug>/",views.LeaveGroup.as_view(),name="leave"),
]

simplesocial/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.HomePage.as_view(), name="home"),
    path('admin/', admin.site.urls),
    path('test/', views.TestPage.as_view(), name="test"),
    path('thanks/', views.ThanksPage.as_view(), name="thanks"),
    path('accounts/', include("accounts.urls", namespace="accounts")),
    path('accounts/', include("django.contrib.auth.urls")),
    # path('posts/', include("posts.urls", namespace="posts")),
    path('groups/',include("groups.urls", namespace="groups")),
    path('register/',include("register.urls", namespace="register")),

]

groups/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from django.utils.text import slugify
import datetime
# from accounts.models import User

# pip install misaka
import misaka

from django.contrib.auth import get_user_model
User = get_user_model()

# https://docs.djangoproject.com/en/2.0/howto/custom-template-tags/#inclusion-tags
# This is for the in_group_members check template tag
from django import template
register = template.Library()


class Guest(models.Model):
    name = models.CharField(max_length=255)
    vehicle_no = models.CharField(max_length=100)
    vehicle_type = models.CharField(max_length=10)
    purpose = models.CharField(max_length=1000)
    in_out = models.CharField(max_length=255,default="Entry")
    time = models.DateTimeField(default=datetime.datetime.now())

    def __str__(self):
        return self.vehicle_no

register/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from django.utils.text import slugify
import datetime
# from accounts.models import User

# pip install misaka
import misaka

from django.contrib.auth import get_user_model
User = get_user_model()

# https://docs.djangoproject.com/en/2.0/howto/custom-template-tags/#inclusion-tags
# This is for the in_group_members check template tag
from django import template
register = template.Library()


class fac(models.Model):
    name = models.CharField(max_length=255)
    vehicle_no = models.CharField(max_length=100)
    vehicle_type = models.CharField(max_length=100)
    des = models.CharField(max_length=1000)
    in_out = models.CharField(max_length=255,default="Entry")
    time = models.DateTimeField(default=datetime.datetime.now())

    def __str__(self):
        return self.vehicle_no

groups/views.py
from django.contrib import messages
from django.contrib.auth.mixins import(
    LoginRequiredMixin,
    PermissionRequiredMixin
)
from django.urls import reverse
from django.db import IntegrityError
from django.shortcuts import get_object_or_404
from django.views import generic
from groups.models import Guest
from . import models
from django.shortcuts import render,redirect
import datetime


def registerVehicle(request):
    if request.method == 'POST':
        obj = Guest()
        obj.name = request.POST["name"]
        obj.vehicle_no = request.POST["vehicle_no"]
        obj.vehicle_type = request.POST["type"]
        obj.purpose = request.POST["purpose"]
        obj.in_out= request.POST["in_out"]
        time = datetime.datetime.now()
        obj.time = time

        obj.save()
        return redirect('/')
    return render(request,'groups/group_base.html')

register/views.py
from django.contrib import messages
from django.contrib.auth.mixins import(
    LoginRequiredMixin,
    PermissionRequiredMixin
)
from django.urls import reverse
from django.db import IntegrityError
from django.shortcuts import get_object_or_404
from django.views import generic
from register.models import fac
from . import models
from django.shortcuts import render,redirect
import datetime

def registerfacVehicle(request):
    if request.method == 'POST':
        obj = fac()
        print("jhgbu")
        obj.name = request.POST["name"]
        obj.vehicle_no = request.POST["vehicle_no"]
        obj.vehicle_type = request.POST["type"]
        obj.des = request.POST["des"]
        obj.in_out= request.POST["in_out"]
        time = datetime.datetime.now()
        obj.time= time
        print("jhgbu")
        obj.save()
        return redirect('/')
    return render(request,'register/register_base.html')

def veh(request):

    try:
         obj = fac.objects.get(vehicle_no=request.POST["vehno"])
         return render(request,'register/register_base.html',{"obj":obj})
         # return render('/register')
        # return redirect('/')
        #fac.objects.filter(vehicle_no=request.POST["vehno"])
        #   return redirect('/register')
    except:
        return redirect('/groups')

templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <title>VE&E</title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <!-- Optional theme -->
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous"> -->

    <!-- Alternative to Bootstrap 3 Glyphicons -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'simplesocial/css/master.css'%}">

  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-dark mynav" role="navigation" id="navbar">
      <div class="container">
        <div class="navbar-nav align-items-center">
          <a class="navbar-brand mynav" href="{% url 'home' %}">Vehicle Entry/Exit Portal!</a>
        </div>
        <div class="navbar-nav ml-auto">
          {% if user.is_authenticated %}
          <a class="nav-item nav-link" href="{% url 'register:all' %}" class="btn btn-simple">REGISTERED VEHICLE</a>

            <a class="nav-item nav-link" href="{% url 'groups:all' %}" class="btn btn-simple">GUEST</a>
            <a class="nav-item nav-link" href="{% url 'accounts:logout' %}" class="btn btn-simple">Log out</a>


          {% else %}
            <a class="nav-item nav-link" href="{% url 'accounts:login' %}" class="btn btn-simple">Log in</a>
            <a class="nav-item nav-link" href="{% url 'accounts:signup' %}" class="btn btn-simple">Sign up</a>
          {% endif %}
        </div>
      </div>
    </nav>

    <div class="container mycontent">
      {% block content %}

      {% endblock %}
    </div>

    <canvas id="canvas"></canvas>

    <script src="{% static "simplesocial/js/master.js"%}" type="text/javascript" ></script>

    <!-- Latest compiled and minified jQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

  </body>
</html>

templates/index.html
{% extends "base.html" %}
{% block content %}

    <h1>Welcome to Vehical Entry/Exit Portal!</h1>


{% endblock %}

templates/test.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <h1>You are now logged in!</h1>
  <h2><a href="{% url 'register:all'%}">Register New Vehicle Portal</a></h2>
  <br><br><br>
  <center>
  <H1 style="color:#ff884d; font-family:verdana;font-size:250%;">Welcome to NITW<br>Please enter your vehicle number:</H1>
  </center>
  <center>
  <br><br><br>
  <form method="POST" action="/register/veh/">
    {% csrf_token %}
    <p style="color:#008080; font-family:courier;font-size:160%;">Vehicle No.:
    <input type="text" ="Vehicle No." name="vehno">
  <!-- </form> -->
  </center></p>
  <br><br><br>
  <center>
  <!-- <form> -->
    <p style="color:#008080; font-family:courier;font-size:160%;">Name:
    <input type="text" ="Name" name="blaaa">
  <!-- </form> -->
  </center></p>
  <br><br><br>
  <center>
  <!-- <form> -->
  <input type="submit" value="Submit">
  </form>
  </center>
</div>

{% endblock %}